name: go_build_test
on: [push]
jobs:
  go_build_test:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.2
      - name: Build      
        run: go build -v ./...
      - name: Test
        run: go test -v ./...